---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_90faf74859f0
          ports:
            - containerPort: 3000  # 컨테이너에서 3000 포트 열기
          env:
            - name: VITE_TMAP_APP_KEY
              valueFrom:
                configMapKeyRef:
                  name: config 
                  key: VITE_TMAP_APP_KEY
            - name: VITE_OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: VITE_OPENAI_API_KEY
            - name: VITE_GOOGLE_MAP_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: VITE_GOOGLE_MAP_API_KEY      
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: NodePort  # 외부 접근을 허용하기 위해 NodePort로 설정
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000  # 원하는 포트 번호 지정 (32000~32767 범위 내에서 선택)
